### PR TITLE
Enforce limits when importing definitions

### LINKED ISSUE #423: Import definitions doesn't apply vhost limits to number of queues
Importing definitions allows to create an unlimited number of queues even when vhost limits are set.

Validation should fail with an option to let the user decide whether or not to proceed, as importing L out of N queues may be OK but the user will not know which ones will be imported. An improvement would be confirmation screen with a warning. Per conversation with @michaelklishin.

### PR DESCRIPTION
**Pull request by lukebakken**
Fixes #423 

Depends on rabbitmq/rabbitmq-server#1282

### CODE REVIEW

File: src/rabbit_mgmt_wm_definitions.erl [hunk 1]
```diff
@@ -426,3 +437,71 @@ rv(VHost, Type, Props) -> rv(VHost, Type, name, Props).
...
+    VHost = maps:get(<<"vhost">>, Q, undefined),
+    Rec = rv(VHost, queue, <<"name">>, Q),
+    {Rec, VHost}.
+
+build_filtered_map([], AccMap) ->
+    {ok, AccMap};
+build_filtered_map([{Rec, VHost}|Rest], AccMap0) ->
+    case rabbit_amqqueue:lookup(Rec) of
+        {error, not_found} ->
+            Count0 = maps:get(VHost, AccMap0, 0),
```
Comment (dcorbacho) [inline src/rabbit_mgmt_wm_definitions.erl]: This update could be simplified with: `AccMap1 = maps:update_with(VHost, fun(V) -> V + 1 end, AccMap0)`

File: src/rabbit_mgmt_wm_definitions.erl [hunk 2]
```diff
@@ -426,3 +437,71 @@ rv(VHost, Type, Props) -> rv(VHost, Type, name, Props).
...
+    case maps:get(queues, All, undefined) of
+        undefined -> ok;
+        Queues0 ->
+            Queues1 = filter_out_existing_queues(VHost, Queues0),
+            AddCount = length(Queues1),
+            validate_vhost_limit(VHost, AddCount, ok)
+    end.
+
+filter_out_existing_queues(Queues) ->
+    QData = [ build_queue_data(Q) || Q <- Queues ],
```
Comment (dcorbacho) [inline src/rabbit_mgmt_wm_definitions.erl]: I don't think is going to be a problem for the import, but it is possible to avoid two passes through the queue list (list comprehension here and `build_filtered_map` just after) by calling `build_queue_data` inside `build_filtered_map` for every queue.  The same applies to `filter_out_existing_queues/2`

**Comment by lukebakken** [comment]
@dcorbacho - my motivation for adding client-side validation is issue #414 which had a large-ish definitions file. These changes avoid the upload. I don't know how often users have large (or larger) files, though. Thanks for the review and I'll make those other changes.

**Comment by michaelklishin** [comment]
Client-side validations are fine as long as they are side by side with validations in the API.

**Comment by lukebakken** [comment]
@michaelklishin I forgot in the summary above to note that this PR depends on rabbitmq/rabbitmq-server#1282 ... I'm pretty sure that's why you got those failures. I got the same set of failures until I checked out the `rabbitmq-management-423` in `deps/rabbit`

**Comment by michaelklishin** [comment]
OK, my bad. Re-trying.
