### PR TITLE
Respond with a Bad Request when client provides double-encoded JSON

### LINKED ISSUE #839: Double encoded JSON payload 500s
* RabbitMQ version 3.8.3
* Erlang version 22.3

```erlang
2020-09-08 11:09:59.674 [error] <0.18927.110> CRASH REPORT Process <0.18927.110> with 0 neighbours crashed with reason: no function clause matching rabbit_mgmt_util:props_as_map(<<"{\"auto_delete\":false,\"durable\":true}">>) line 875
```

```erlang
2020-09-08 11:09:59.974 [error] <0.17898.110> Ranch listener rabbit_web_dispatch_sup_15672, connection process <0.17898.110>, stream 64 had its request process <0.18936.110> exit with reason function_clause and stacktrace [{rabbit_mgmt_util,props_as_map,[<<"{\"auto_delete\":false,\"durable\":true}">>],[{file,"src/rabbit_mgmt_util.erl"},{line,875}]},{rabbit_mgmt_util,with_vhost_and_props,3,[{file,"src/rabbit_mgmt_util.erl"},{line,890}]},{cowboy_rest,call,3,[{file,"src/cowboy_rest.erl"},{line,1576}]},{cowboy_rest,process_content_type,3,[{file,"src/cowboy_rest.erl"},{line,1100}]},{cowboy_rest,upgrade,4,[{file,"src/cowboy_rest.erl"},{line,288}]},{cowboy_stream_h,execute,3,[{file,"src/cowboy_stream_h.erl"},{line,296}]},{cowboy_stream_h,request_process,3,[{file,"src/cowboy_stream_h.erl"},{line,274}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,249}]}]
```

It looks like because its still a binary, its failing to match the function head

```erlang
props_as_map(Val) when is_map(Val)  -> Val;
props_as_map(null)                  -> #{};
props_as_map(undefined)             -> #{};
props_as_map(Val) when is_list(Val) -> maps:from_list(Val).
```

I'm not super familiar with `try/catch` in erlang, but it seems like either the `try` block doesn't exist in 3.8.3, or it is not matching the `:error` type. 

I could be interested in fixing myself, but I might need a little bit of help.

### PR DESCRIPTION
**Pull request by michaelklishin**
instead of a 500.

@lukebakken I would understand if addressing this would be considered to be "too much" but looks like it's a pretty safe and minor change.

To run a focussed test:

``` shell
gmake ct-rabbit_mgmt_only_http t="all_tests_without_prefix:double_encoded_json_test"
```

Closes #839.

### CODE REVIEW

File: src/rabbit_mgmt_util.erl [hunk 1]
```diff
@@ -810,7 +810,13 @@ decode(<<"">>) ->
     {ok, #{}};
 decode(Body) ->
     try
-        {ok, rabbit_json:decode(Body)}
+        %% handle double encoded JSON, see rabbitmq/rabbitmq-management#839
+        case rabbit_json:decode(Body) of
+            Val when is_map(Val)    -> {ok, Val};
+            Val when is_list(Val)   -> {ok, maps:from_list(Val)};
```
Comment (michaelklishin) [inline src/rabbit_mgmt_util.erl:816]: Maybe we should not assume that the list is a proplist… It is perfectly fine to pass an array as a JSON-encoded body. But we don't currently have any API endpoints that uses such a payload, so… @lukebakken

**Comment by lukebakken** [comment]
I'm planning to test and review this today!

File: src/rabbit_mgmt_util.erl [hunk 2]
```diff
@@ -810,7 +810,13 @@ decode(<<"">>) ->
...
+            Bin when is_binary(Bin) -> {error, not_json};
```
Comment (lukebakken) [inline src/rabbit_mgmt_util.erl:817]: Hmm. As you said [here](https://github.com/rabbitmq/rabbitmq-management/issues/839#issuecomment-689239110) doubly-encoded JSON _is valid JSON_.

Can we return something other than `not_json`?

Comment (lukebakken) [reply src/rabbit_mgmt_util.erl]: See [this commit](https://github.com/rabbitmq/rabbitmq-management/pull/848/commits/cd8ed9f97a5ca0634c4f3cd23e1842641b6e03be). Feel free to rebase and drop it if you'd like, however!

Comment (michaelklishin) [reply src/rabbit_mgmt_util.erl]: We can indicate that the payload was invalid (not invalid JSON per se). Discussed on Slack.

**Comment by michaelklishin** [comment]
Backported to `v3.8.x`.
